### ISSUE TITLE
Question: données Gapminder

### ISSUE THREAD

**Issue by GabrielleDesrosiersBrisebois** [GabrielleDesrosiersBrisebois/FAS1002_projet-final#1]
Salut @SamGuay,

J'ai été en mesure d'écrire un petit script pour télécharger et sauvegarder le fichier ".csv" des données liées à la vaccination de façon quotidienne. Par contre, je souhaite valider les consignes pour les banques de données "Gapminder". Il faut seulement télécharger de nouveau les fichiers une fois par mois, même si ces banques de données ne sont pas mises à jour mensuellement. Ai-je bien compris?

Merci et bonne soirée!

**Comment by SamGuay** [comment]
Oui, c'est bien ça! En gros, selon comment tu as construit ton code, il n'y devrait avoir que la fréquence qui change pour y arriver.

**Comment by GabrielleDesrosiersBrisebois** [comment]
Super, merci de la précision!
