### ISSUE TITLE
Question: nouvelle variable continent

### ISSUE THREAD

**Issue by GabrielleDesrosiersBrisebois** [GabrielleDesrosiersBrisebois/FAS1002_projet-final#2]
Salut @SamGuay, 

Concernant la création de la variable `continent`, est-il possible d'aller chercher une autre banque de données (p. ex. https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv) contenant déjà la liste des pays et leur continent associé, et joindre celle-ci à mes autres données? Ou faut-il absolument entrer manuellement ces informations? Je sais qu'il est possible d'incorporer d'autres jeux de données pour produire nos analyses, mais je voulais simplement vérifier qu'il était aussi possible de le faire pour exécuter cette tâche. 

Merci et bonne soirée!

**Comment by SamGuay** [comment]
Hello! 
Tu peux faire comme bon te semble! La programmeuse en toi devrait pencher vers la solution la plus simple/paresseuse :smile:

**Comment by GabrielleDesrosiersBrisebois** [comment]
Super merci! J'espérais pouvoir prendre ces données parce que la solution manuelle est beaucoup plus longue 😂
