### ISSUE TITLE
Question: variable temps entre le moment de produire le rapport et données de vaccination par pays

### ISSUE THREAD

**Issue by GabrielleDesrosiersBrisebois** [GabrielleDesrosiersBrisebois/FAS1002_projet-final#3]
Allô @SamGuay,

Désolée, j'ai encore une question concernant l'une des consignes. 

Pour déceler la date des données de vaccination les plus récentes pour chacun des pays j'ai produit le petit code suivant :

`recent_data <- df_countries %>% 
  group_by(name) %>% 
  summarise(most_recent_date = format(max(as_date(date)))) %>% 
  ungroup()` 

![image](https://user-images.githubusercontent.com/90478586/146661035-4d955ea5-a099-4107-ac18-d892b8ffec66.png)

Avec ces informations, je veux créer un graphique illustrant la donnée la plus récente pour chaque pays, afin de souligner l'écart entre les divers pays. Bien que ce calcul n'indique pas explicitement le temps écoulé entre les données et la date de production du rapport, est-ce qu'il correspond tout de même à ce que tu veux que l'on illustre par le biais de cette consigne ou une unité de temps doit absolument être présente?

Merci à l'avance et bonne soirée!

**Comment by SamGuay** [comment]
Bon matin, 
Pour ma part, ça semble suffisamment sophistiqué pour évaluer tes capacités!
J'ai hâte de voir le graphique! :chart_with_upwards_trend:

**Comment by GabrielleDesrosiersBrisebois** [comment]
Parfait, merci!
